#ifndef ROBOTMOVEMENT_H
#define ROBOTMOVEMENT_H
namespace yolo {
enum class RobotMovement {
    MOVE_STRAIGHT = 1,
    MOVE_TURNRIGHT = MOVE_STRAIGHT + 1,
    MOVE_TURNLEFT = MOVE_STRAIGHT + 2,
    MOVE_UTURN = MOVE_STRAIGHT + 3,
    MOVE_AVOID = MOVE_STRAIGHT + 4,
    MOVE_PUSHCAN = MOVE_STRAIGHT + 5,
    MOVE_STOP = MOVE_STRAIGHT + 6,
    MOVE_GO = MOVE_STRAIGHT + 7
};
}

#endif // ROBOTMOVEMENT_H
